-define(IAC, $\xff).
-define(DO, $\xfd).
-define(DONT, $\xfe).
-define(WILL, $\xfb).
-define(WONT, $\xfc).
-define(SB, $\xfa).
-define(SE, $\xf0).
-define(AYT, $\xf6).
-define(EOR, 239).
-define(GA, 249).

-define(SUPPRESS_GO_AHEAD, 3).
-define(END_OF_RECORD, 25).
